### PR TITLE
Update to Swift 3 and recommended project settings

### PR DESCRIPTION
**Pull request by kiliankoe**
Just tried out my project using Log with Swift 3 in the Xcode 8 Beta. Looks like there's currently no Swift 3 compatible branch here. It'd be great if you could merge this into a currently non existent branch on your repo or make the changes yourself if you want and close this PR.

Thanks 😊

### CODE REVIEW

**Comment by delba** [comment]
That's awesome! I was just talking with someone who's porting another of my project in `swift-3.0` https://github.com/hartbit/Permission/commit/5f7f606542015c966c7156cda69034eefaf079a1 ahaha

You guys are awesome! I'm gonna create a `swift-3.0` branch and merge it tomorrow!

Thank you so much!

**Comment by kiliankoe** [comment]
That's awesome! You're not at WWDC by any chance, are you? 😄

**Comment by delba** [comment]
Nope 😒 

😃

**Comment by kiliankoe** [comment]
That's a shame. Had the slight hope of meeting you here after you mentioned you were "talking with someone" 😜

**Comment by delba** [comment]
Hey @kiliankoe ,

Sorry for the late response, I had a busy weekend.

I just pushed the `swift-3.0` branch. I'm closing this PR. Could you please create a new one to merge on the new branch? 

Thanks!

**Comment by kiliankoe** [comment]
Umm, I have to admit I'm kinda stumped here... Is there a reason for starting the new branch completely fresh? I thought I knew my way around git, but I can't manage to send a mergeable PR to the new branch without basically just copying the entire directory over 😕 
If you want you can also go ahead and just run the Xcode 8 migrator yourself if that makes things easier. That's basically everything I did 😊

**Comment by delba** [comment]
My bad! I fixed it, it should be good now :)

**Pull request closed without merging**
